# Generated by Django 5.0.1 on 2024-03-02 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_pedido', models.CharField(choices=[('AT', 'A tiempo'), ('A', 'Atrasado'), ('CNE', 'Cliente no encontrado')], default='AT', max_length=3)),
                ('etapa_pedido', models.CharField(choices=[('LPE', 'Listo para entregar'), ('RA', 'Repartidor asignado'), ('E', 'Embarcado'), ('PNE', 'Paquete no entregado'), ('PE', 'Paquete entregado')], default='LPE', max_length=3)),
                ('fecha_listo_para_entregar', models.DateField()),
                ('cliente_no_encontrado', models.BooleanField(default=False)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.vendedor')),
            ],
        ),
    ]
