# Generated by Django 5.0.1 on 2024-03-03 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoG3',
            fields=[
                ('pedidoID', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_listo_para_entregar', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductoG3',
            fields=[
                ('productoID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
                ('costo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ReporteG3',
            fields=[
                ('reporteID', models.AutoField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField(null=True)),
                ('mes', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendedorG3',
            fields=[
                ('vendedorID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleDePedidoG3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='marketplace.pedidog3')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.productog3')),
            ],
        ),
        migrations.CreateModel(
            name='RecomendacionGR3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(choices=[('OFERTA_DE_PRODUCTOS', 'Crear oferta en los productos para generar más ventas.'), ('MANTENER_PROMOCION_DE_PRODUCTOS', 'Aumentar tu meta para el siguiente mes.'), ('COMBO_DE_PRODUCTO', 'Crear combos o conjunto de productos similares.'), ('PROMOCION_PRODUCTOS_ESTRELLA', 'Promocionar productos estrella.'), ('NEGOCIAR_DESCUENTO', 'Negociar descuentos con proveedores o buscar alternativas más económicas.'), ('OPTIMIZAR_PROCESOS', 'Optimizar procesos internos para reducir costos operativos.'), ('AJUSTAR_PRECIO_SOBRE_COSTO', 'Ajustar los precios de los productos con respecto a sus costos.'), ('MANTENER_PRECIO_SOBRE_COSTO', 'Mantener los precios de los productos con respecto a sus costos.')], max_length=31)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='marketplace.reporteg3')),
            ],
        ),
        migrations.CreateModel(
            name='MetricaG3',
            fields=[
                ('metricaID', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_de_metrica', models.CharField(choices=[('NV', 'Número de ventas'), ('IS', 'Ingresos'), ('CS', 'Costos'), ('BV', 'Beneficio por venta')], max_length=19)),
                ('valor', models.FloatField(null=True)),
                ('anio', models.IntegerField(null=True)),
                ('mes', models.IntegerField(null=True)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metricas', to='marketplace.reporteg3')),
            ],
        ),
        migrations.AddField(
            model_name='reporteg3',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='marketplace.vendedorg3'),
        ),
        migrations.AddField(
            model_name='productog3',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='marketplace.vendedorg3'),
        ),
        migrations.AddField(
            model_name='pedidog3',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='marketplace.vendedorg3'),
        ),
        migrations.CreateModel(
            name='MetaG3',
            fields=[
                ('metaID', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_de_metrica', models.CharField(choices=[('NV', 'Número de ventas'), ('IS', 'Ingresos'), ('CS', 'Costos'), ('BV', 'Beneficio por venta')], max_length=2)),
                ('valor', models.FloatField(null=True)),
                ('anio', models.IntegerField(null=True)),
                ('mes', models.IntegerField(null=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='marketplace.vendedorg3')),
            ],
        ),
    ]
