# Generated by Django 5.0.1 on 2024-03-04 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_real_etapa_listo_para_entregar',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_real_etapa_precompra',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_real_etapa_reserva',
        ),
    ]
