# Generated by Django 5.0.1 on 2024-03-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa_pedido', models.CharField(choices=[('PC', 'Precompra'), ('R', 'Reserva'), ('LE', 'Listo para entregar')], default='PC', max_length=2)),
                ('estado_pedido', models.CharField(choices=[('AT', 'A tiempo'), ('A', 'Atrasado'), ('C', 'Cancelado')], default='AT', max_length=2)),
                ('fecha_creacion_pedido', models.DateField()),
                ('fecha_real_etapa_precompra', models.DateField(blank=True, null=True)),
                ('fecha_real_etapa_reserva', models.DateField(blank=True, null=True)),
                ('fecha_real_etapa_listo_para_entregar', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
