# Generated by Django 5.0.1 on 2024-03-04 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_remove_promocion_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='supera_record',
            field=models.BooleanField(default=False),
        ),
    ]
