# Generated by Django 5.0.1 on 2024-03-04 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_remove_pedido_fecha_real_etapa_listo_para_entregar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='marketplace.cliente'),
        ),
    ]
