# Generated by Django 5.0.1 on 2024-03-02 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_calificacion_remove_producto_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id_producto',
            field=models.AutoField(default=0, primary_key=True, serialize=False, unique=True),
        ),
    ]
