# Generated by Django 5.0.1 on 2024-03-02 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pedido_activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='vendedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='marketplace.vendedor'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado_pedido',
            field=models.CharField(choices=[('AT', 'a_tiempo'), ('A', 'atrasado'), ('C', 'cancelado')], default='AT', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='etapa_pedido',
            field=models.CharField(choices=[('PC', 'precompra'), ('R', 'reserva'), ('LE', 'listo_para_entregar')], default='PC', max_length=20),
        ),
    ]
