# Generated by Django 5.0.1 on 2024-03-02 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_calificacion_producto_calificaciones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='calificaciones_recibidas',
        ),
        migrations.AddField(
            model_name='calificacion',
            name='causas',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='estrellas',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado_pedido', models.CharField(max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='marketplace.cliente')),
                ('lista_de_productos', models.ManyToManyField(to='marketplace.producto')),
            ],
        ),
    ]
