# Generated by Django 5.0.1 on 2024-03-02 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_cliente_remove_producto_calificaciones_recibidas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='id_producto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='marketplace.producto'),
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuaciones_calificaciones', models.JSONField(default=dict)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Servicio', to='marketplace.pedido')),
            ],
        ),
        migrations.AddField(
            model_name='calificacion',
            name='id_servicio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='marketplace.servicio'),
        ),
    ]
